// <auto-generated />
namespace Week5Assignment.domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddYearsEmployedPage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddYearsEmployedPage));
        
        string IMigrationMetadata.Id
        {
            get { return "201811112255118_Add Years Employed Page"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
